name: teardown

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Show env
        run: |
          cat /etc/os-release
          echo $AWS_DEFAULT_REGION
          echo ${{github.head_ref}}

      - name: Terraform workspace
        run: |
          make workspace WS=${{github.head_ref}}

      - name: Terraform init
        run: |
          make init

      - name: Terraform destroy
        run: |
          make destroy